<?php

use NunoMaduro\PhpInsights\Domain\Insights\Composer\ComposerMustContainName;
use NunoMaduro\PhpInsights\Domain\Insights\CyclomaticComplexityIsHigh;
use NunoMaduro\PhpInsights\Domain\Insights\ForbiddenDefineFunctions;
use NunoMaduro\PhpInsights\Domain\Insights\ForbiddenNormalClasses;
use ObjectCalisthenics\Sniffs\Files\ClassTraitAndInterfaceLengthSniff;
use ObjectCalisthenics\Sniffs\Files\FunctionLengthSniff;
use ObjectCalisthenics\Sniffs\Metrics\MethodPerClassLimitSniff;
use PHP_CodeSniffer\Standards\Generic\Sniffs\Files\LineLengthSniff;
use SlevomatCodingStandard\Sniffs\Classes\SuperfluousExceptionNamingSniff;
use SlevomatCodingStandard\Sniffs\TypeHints\DisallowMixedTypeHintSniff;
use SlevomatCodingStandard\Sniffs\TypeHints\DisallowArrayTypeHintSyntaxSniff;
use SlevomatCodingStandard\Sniffs\Commenting\DocCommentSpacingSniff;
use SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff;
use SlevomatCodingStandard\Sniffs\TypeHints\ParameterTypeHintSniff;
use SlevomatCodingStandard\Sniffs\TypeHints\PropertyTypeHintSniff;
use SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSniff;

return [

    'ide' => 'vscode',

    'remove' => [
        // @TB: Support helpers.php
        ForbiddenDefineFunctions::class,

        // @TB: Support CustomException naming convention
        SuperfluousExceptionNamingSniff::class,

        // @TB: Not important / not enforced in Laravel / varies from IDEs.
        ComposerMustContainName::class,
        ForbiddenNormalClasses::class,
        LineLengthSniff::class,
        ParameterTypeHintSniff::class,
        PropertyTypeHintSniff::class,
        ReturnTypeHintSniff::class,
        MethodPerClassLimitSniff::class, // Models will usually have many methods due to relationships

        // @TB: Flags type hints generated by laravel-ide-helper required by phpstan
        DisallowArrayTypeHintSyntaxSniff::class,
        DisallowMixedTypeHintSniff::class,
        DocCommentSpacingSniff::class,
    ],

    // @TB: Most controllers will be lengthy, but this should be max enough.
    'config' => [

        ClassTraitAndInterfaceLengthSniff::class => [
            'maxLength' => 700, // FunctionLengthSniff.maxLength * 7 resource controller methods
        ],

        FunctionLengthSniff::class => [
            'maxLength' => 100, // Default is 20  * default CyclomaticComplexityIsHigh.maxComplexity
        ],

        // @TB: https://github.com/nunomaduro/phpinsights/issues/367
        CyclomaticComplexityIsHigh::class => [
            'maxComplexity' => 35, // Default is 5 * 7 resource controller methods
        ],

        // @TB: Prevents false positives caused by mpociot/laravel-apidoc-generator
        UnusedUsesSniff::class => [
            'exclude' => ['app/Http/Controllers/Api'],
        ]
    ],

];
